builds:
  - binary: dnclist
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: dnc-list-search
    homepage: https://github.com/keyglee/dnc-list-search
    commit_author:
      name: Ryley Lamb
      email: ryleylamb@gmail.com

checksum:
  name_template: 'checksums.txt'