version: 2

builds:
  - binary: dnclistsearch
    main: ./main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=mod
    mod_timestamp: "{{ .CommitTimestamp }}"

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: dnclistsearch
    homepage: https://github.com/keyglee/dnclistsearch
    commit_author:
      name: Ryley Lamb
      email: ryleylamb@gmail.com

checksum:
  name_template: checksums.txt
